### ISSUE TITLE
Metronome breaks when 00 is inputted

### ISSUE THREAD

**Issue by melissalupu** [adaapp/testing-dec2021-team3#34]
<img width="1440" alt="Screenshot 2022-01-18 at 11 56 26" src="https://user-images.githubusercontent.com/54673305/149933087-5cd500a8-7e23-417b-9e2b-69f91fe88e4e.png">

**Comment by elijaholan** [comment]
Fixed in the latest pull request, uses the sanitiseBeat() helper function:

![image](https://user-images.githubusercontent.com/90607671/150106982-8f28f7b6-8616-4c56-8c80-0ae553a27243.png)
