### ISSUE TITLE
Not all black keys maintaining the set pattern of 2 (space) 3 (space) 2 ...

### ISSUE THREAD

**Issue by melissalupu** [adaapp/testing-dec2021-team3#36]
![Screenshot 2022-01-18 at 13 48 36 (2)](https://user-images.githubusercontent.com/54673305/149949717-81916cd1-81b4-42e6-8601-cf39e7cc8746.png)

**Comment by elijaholan** [comment]
Looks good now, fixed through the isKeyBlack() helper function:

![image](https://user-images.githubusercontent.com/90607671/150107131-4f75f22b-4198-444a-a752-840ae5ff16e5.png)
