### ISSUE TITLE
Make a project board, one for the whole team. Use issues as tickets. 

### ISSUE THREAD

**Issue by missKatiaPunter** [adaapp/testing-dec2021-team3#4]

**Comment by brunogrcsada** [comment]
The project tracker was used throughout the development of the app, all of the tickets were stored here, and moved automatically depending on their state :). Every ticket and pull request had assignees and labels, ensuring organisation!

![image](https://user-images.githubusercontent.com/54673205/150261688-cbcd0988-d9c9-4fb4-a880-80f5fcfcb71a.png)
