### ISSUE TITLE
Dependabot is listing 2 outdated packages that need to be fixed

### ISSUE THREAD

**Issue by melissalupu** [adaapp/testing-dec2021-team3#40]
<img width="924" alt="Screenshot 2022-01-19 at 10 26 13" src="https://user-images.githubusercontent.com/54673305/150112284-4c61691e-3942-45d4-9da1-c2f674d204ea.png">

**Comment by brunogrcsada** [comment]
This is an issue related to dependencies which react-scripts depends on, and has been mentioned publicly by other developers. I've modified the package-lock.json file and disabled further warnings from Dependabot.
